#pragma once

#define NUM_PLAYERS 2

#define BASE_RESOURCE_COST 2
#define MARKET_RESOURCE_COST 1
#define BASE_DISCARD_COINS 2
#define URBANISM_COINS_PER_CHAIN 4
#define COIN_PACKET_SIZE 3

#define MILITARY_SCORE_1 2
#define MILITARY_SCORE_2 5
#define MILITARY_SCORE_3 10
#define MILITARY_THRESHOLD_1 1
#define MILITARY_THRESHOLD_2 3
#define MILITARY_THRESHOLD_3 6
#define MILITARY_THRESHOLD_WIN 9

#define SCIENCE_THRESHOLD_WIN 6

#define MAX_WONDERS_BUILT 7

#define NUM_GAME_TOKENS 5
#define NUM_BOX_TOKENS 3
