#pragma once

#define EXC_NOT_ENOUGH_COINS 100
#define EXC_OBJECT_NOT_AVALIABLE 101
#define EXC_MAX_WONDERS_BUILT 102
#define EXC_UNEXPECTED_MOVE 103

#define EXC_INCORRECT_DECK 200
#define EXC_ALREADY_REVEALED 201
#define EXC_ALREADY_A_GUILD 202
#define EXC_GAME_ENDED 203
#define EXC_UNEXPECTED_REVEAL 204

#define EXC_DECK_EMPTY 300
#define EXC_DECK_FULL 301
#define EXC_NOT_IN_DECK_POS 302
#define EXC_OBJ_ALREADY_IN_DECK 303
#define EXC_UNEXPECTED_SCHEDULED 304
#define EXC_EXPECTED_SCHEDULED 305
