#include "object_decks.h"

const std::array<int, NUM_AGE_1_CARDS> age1Cards = {
    O_BROWN_LUMBER_YARD,
    O_BROWN_LOGGING_CAMP,
    O_BROWN_CLAY_POOL,
    O_BROWN_CLAY_PIT,
    O_BROWN_QUARRY,
    O_BROWN_STONE_PIT,
    O_GRAY_GLASSWORKS,
    O_GRAY_PRESS,
    O_BLUE_THEATER,
    O_BLUE_ALTAR,
    O_BLUE_BATHS,
    O_RED_STABLE,
    O_RED_GARRISON,
    O_RED_PALISADE,
    O_RED_GUARD_TOWER,
    O_GREEN_SCRIPTORIUM,
    O_GREEN_PHARMACIST,
    O_GREEN_WORKSHOP,
    O_GREEN_APOTHECARY,
    O_YELLOW_TAVERN,
    O_YELLOW_STONE_RESERVE,
    O_YELLOW_CLAY_RESERVE,
    O_YELLOW_WOOD_RESERVE
};

const std::array<int, NUM_AGE_2_CARDS> age2Cards = {
    O_BROWN_SAWMILL,
    O_BROWN_BRICKYARD,
    O_BROWN_SHELF_QUARRY,
    O_GRAY_GLASSBLOWER,
    O_GRAY_DRYING_ROOM,
    O_BLUE_STATUE,
    O_BLUE_TEMPLE,
    O_BLUE_AQUEDUCT,
    O_BLUE_ROSTRUM,
    O_BLUE_TRIBUNAL,
    O_RED_HORSE_BREEDERS,
    O_RED_BARRACKS,
    O_RED_ARCHERY_RANGE,
    O_RED_PARADE_GROUND,
    O_RED_WALLS,
    O_GREEN_LIBRARY,
    O_GREEN_DISPENSARY,
    O_GREEN_SCHOOL,
    O_GREEN_LABORATORY,
    O_YELLOW_BREWERY,
    O_YELLOW_FORUM,
    O_YELLOW_CARAVANSERY,
    O_YELLOW_CUSOMS_HOUSE
};

const std::array<int, NUM_AGE_3_CARDS> age3Cards = {
    O_BLUE_GARDENS,
    O_BLUE_PANTHEON,
    O_BLUE_SENATE,
    O_BLUE_PALACE,
    O_BLUE_TOWN_HALL,
    O_BLUE_OBELISK,
    O_RED_FORTIFICATIONS,
    O_RED_SIEGE_WORKSHOP,
    O_RED_CIRCUS,
    O_RED_ARSENAL,
    O_RED_COURTHOUSE,
    O_GREEN_UNIVERSITY,
    O_GREEN_OBSERVATORY,
    O_GREEN_ACADEMY,
    O_GREEN_STUDY,
    O_YELLOW_LIGHTHOUSE,
    O_YELLOW_ARENA,
    O_YELLOW_CHAMBER_OF_COMMERCE,
    O_YELLOW_PORT,
    O_YELLOW_ARMORY
};

const std::array<int, NUM_GUILD_CARDS> guildCards = {
    O_GUILD_MERCHANTS_GUILD,
    O_GUILD_SHIPOWNERS_GUILD,
    O_GUILD_BUILDERS_GUILD,
    O_GUILD_MAGISTRATES_GUILD,
    O_GUILD_SCIENTISTS_GUILD,
    O_GUILD_MONEYLENDERS_GUILD,
    O_GUILD_TACTICIANS_GUILD
};

const std::array<int, NUM_TOKENS> tokens = {
    O_TOKEN_AGRICULTURE,
    O_TOKEN_ARCHITECTURE,
    O_TOKEN_ECONOMY,
    O_TOKEN_LAW,
    O_TOKEN_MASONRY,
    O_TOKEN_MATHEMATICS,
    O_TOKEN_PHILOSOPHY,
    O_TOKEN_STRATEGY,
    O_TOKEN_THEOLOGY,
    O_TOKEN_URBANISM
};

const std::array<int, NUM_WONDERS> wonders = {
    O_WONDER_THE_APPIAN_WAY,
    O_WONDER_CIRCUS_MAXIMUS,
    O_WONDER_THE_COLOSSUS,
    O_WONDER_THE_GREAT_LIBRARY,
    O_WONDER_THE_GREAT_LIGHTHOUSE,
    O_WONDER_THE_HANGING_GARDENS,
    O_WONDER_THE_MAUSOLEUM,
    O_WONDER_PIRAEUS,
    O_WONDER_THE_PYRAMIDS,
    O_WONDER_THE_SPHINX,
    O_WONDER_THE_STATUE_OF_ZEUS,
    O_WONDER_THE_TEMPLE_OF_ARTEMIS
};

const std::array<int, NUM_LOOTINGS> lootings = {
    O_LOOTING_LOOTING_1,
    O_LOOTING_LOOTING_2
};
